### PR TITLE
Upgrade to storm 1.0.2 version

### PR DESCRIPTION
**Pull request by sachingsachin**
1) Version upgrade in pom.xml
2) Change package names s/backtype/org.apache/g
3) Add clojure dependency
4) Resolve ByteBuffer to byte[] conversions

One test still failing - needs some mockito fixing.

### CODE REVIEW

**Comment by sachingsachin** [comment]
Hey @akaIDIOT , Do you have any plans to move to the next version of Storm? We can work on this PR to do the same. Storm 1.0.2 brings several good features like Nimbus HA, Heartbeart Monitor and Debug Tuples etc.

**Comment by akaIDIOT** [comment]
Hey @sachingsachin, sorry for my late reply. As you can see the other PR open for this repo, I started the upgrade myself too, but for version 1.0.0. I think that PR was awaiting testing in production before merging it. Our production environment has the storm component disabled, currently, so that turned out more complicated than I'd wanted. Assuming there's more people interested in upgrading this project to 1.0+, we could indeed combine our efforts to make this happen. 

Considering the PR for 1.0.0 has all of the tests fixed, *could you create a pull request upgrading from 1.0.0 to 1.0.2 with branch `storm-1.0.0` as the target?* I'm hoping the only required change for that would the version in the pom. If you're able to verify it all works in a real-world environment, I'd be willing to merge this. 

Last remaining snag is that I won't be at work for a few weeks, so unable to push a signed release of the update to maven central. But let's cross that bridge when we reach it, shall we? :smile:

**Comment by sachingsachin** [comment]
Hey @akaIDIOT, I do not have free cycles to do a complete thorough testing. How about we fix the current tests, bump up the **major** project version and make a release? Obvious problems from the upgrade will be taken care by the existing tests in this repo (I haven't looked at them thoroughly though) and any deep rooted problems will be found by anyone testing the newer version. Development on kafka-spout with older storm version can still continue on a branch.

**Comment by akaIDIOT** [comment]
Bypassed all current PR's and moved 0.4 to storm-core 1.1.0. Will release 0.4 to maven central as soon as I can! Thanks for the effort though!

**Pull request closed without merging**
